bin/hipify-perl
src/CUDA2HIP_SPARSE_API_functions.cpp

+ Based on:
https://github.com/ROCmSoftwarePlatform/hipSPARSE/pull/102
https://github.com/ROCmSoftwarePlatform/hipSPARSE/pull/103
+ bsrmv and csr2csr_compress functions support

[HIPIFY][SPARSE] sync with hipSPARSE's #102 and #103

---

tests/unit_tests/libraries/cuSPARSE/cuSPARSE_12.cu

[Reason] cusparseDbsrmv is supported now:
https://github.com/ROCmSoftwarePlatform/hipSPARSE/pull/102
https://github.com/ROCm-Developer-Tools/HIPIFY/pull/96

[HIPIFY][tests][SPARSE] Update cuSPARSE_12.cu test

---

CMakeLists.txt
packaging/hipify-clang.txt

Add capability to build package as per user choice.
If the parameter CPACK_PACKAGING_INSTALL_PREFIXX is not provided, 
default to /opt/rocm/hip

[HIPIFY] Set configurable install path

---

src/StringUtils.h

The issue appeared with VS 2019 16.6.0, where std is redesigned to support some C++20 features.

[HIPIFY][fix] Explicit #include <system_error> for std::error_code

---

tests/unit_tests/libraries/cuRAND/benchmark_curand_kernel.cpp

Unsupported API GL cuGLInit was not only reported as unsupported and deprecated but led to an error due to the missing include to cudaGL.h.
cuGLInit was added to the test for testing warning on deprecated API.
[ToDo] Tests on different types of warnings.

[HIPIFY][fix] Remove unsupported CUDA API from a cuRAND test

---

src/main.cpp

Instead of proposed in #126 removing of the corresponding clang source include paths, the analogous include paths to hipify-clang dist was changed:
`-isystem <dist>/include` => `-Xclang -internal-isystem -Xclang <dist>/include`
`-isystem <dist>/include/cuda_wrapper` => `-Xclang -internal-isystem -Xclang <dist>/include/cuda_wrapper`
It allows coexisting both source clang includes and hipify-clang dist includes. If source LLVM/clang is deleted/renamed or moved installed hipify-clang continue works properly using its header files from dist/include subfolder.
This PR fixes #92 as well.

[HIPIFY][#92][#126] Fix clang internal includes

---

README.md

* by LLVM starting with 10.0 version.
[ToDo]
1. Fix failed unit tests: #130 - #132
2. Support CUDA RT API and CUDA Driver API changes, including deprecated and removed APIs
3. Support all CUDA libs changes
4. Update markdown docs accordingly

[HIPIFY][doc] CUDA 11.0 is supported*

---

tests/lit.cfg

[Reason] cuDNN v.8.0 for CUDA 11 is changed a lot: many APIs were removed, for instance, cudnnGetConvolutionForwardAlgorithm().

[HIPIFY][tests][#132] Exclude cudnn_convolution_forward.cu test if CUDA 11.0 and higher

---

tests/lit.cfg

[Reason] cuSPARSE for CUDA 11 is changed a lot: many deprecated APIs were removed
[ToDo] Implement alternate cuSparse tests for CUDA 11

[HIPIFY][tests][#131] Exclude cuSparse 01, 02, and 12 tests if CUDA 11.0 and higher

---

bin/hipify-perl
src/CUDA2HIP_Driver_API_functions.cpp
src/CUDA2HIP_Driver_API_types.cpp

+ Functions and data types from cuda.h only
[ToDo] Update HIP's CUDA_Driver_API_functions_supported_by_HIP.md and hipify-perl accordingly

[HIPIFY] CUDA 11.0 Driver API support

---

README.md

`CUDA 11.0 RC`, `cuDNN 8.0.1.13`, and `LLVM 10.0.1-rc2` are supported; unit tests are passed.

[HIPIFY][doc] README.md update

---

README.md
tests/lit.cfg

+ Confirmation: hipify-clang work smoothly with former LLVM versions from 4.0.x to 10.0.x
+ LLVM 3.x is not supported anymore but might still work
+ Update Readme.md and lit testing accordingly

[HIPIFY][doc][tests] Revise functionality with the former LLVM versions

---

src/CUDA2HIP_Perl.cpp

Hi All, this is a quick pull to fix a bug with the whitelist behaviour of hipify-perl.  The bug is as follows: The regular expression which replaces the whitelisted 'cudaXXXX' function call with 'ZAP' acts on the first occurrence of the whitelisted 'cudaXXX' and then goes on to the next line. As such it doesn't appropriately ignore lines such as:
``` void cloverDerivative(
cudaGaugeField &force, cudaGaugeField &gauge, cudaGaugeField &oprod, double coeff, QudaParity parity)```
where the line 
``` cudaGaugeField &force, cudaGaugeField &gauge, cudaGaugeField &oprod, double coeff, QudaParity parity)```
is only zapped to 
```ZAP &force, cudaGaugeField &gauge, cudaGaugeField &oprod, double coeff, QudaParity parity)```
By inserting `redo if` in front of the regex  doing the zapping, as is done …

[HIPIFY][perl] Added redo if to the generated PERL

---

src/CUDA2HIP.cpp
src/CUDA2HIP.h
src/CUDA2HIP_BLAS_API_functions.cpp
src/CUDA2HIP_BLAS_API_types.cpp
src/CUDA2HIP_CAFFE2_API_functions.cpp
src/CUDA2HIP_CAFFE2_API_types.cpp
src/CUDA2HIP_CUB_API_types.cpp
src/CUDA2HIP_Complex_API_functions.cpp
src/CUDA2HIP_Complex_API_types.cpp
src/CUDA2HIP_DNN_API_functions.cpp
src/CUDA2HIP_DNN_API_types.cpp
src/CUDA2HIP_Device_functions.cpp
src/CUDA2HIP_Driver_API_functions.cpp
src/CUDA2HIP_Driver_API_types.cpp
src/CUDA2HIP_FFT_API_functions.cpp
src/CUDA2HIP_FFT_API_types.cpp
src/CUDA2HIP_RAND_API_functions.cpp
src/CUDA2HIP_RAND_API_types.cpp
src/CUDA2HIP_Runtime_API_functions.cpp
src/CUDA2HIP_Runtime_API_types.cpp
src/CUDA2HIP_SPARSE_API_functions.cpp
src/CUDA2HIP_SPARSE_API_types.cpp
src/Statistics.cpp
src/Statistics.h

Preliminary steps for #172 implementation.
[ToDo]
Decide whether to do the same for ROCm/HIP-clang versioning or not.
Implement initial Markdown documentation generation for a single API (Runtime, Driver, or SPARSE).

[HIPIFY] Add initial support of CUDA deprecated and removed APIs' versioning

---

bin/hipify-perl
src/CUDA2HIP_Runtime_API_functions.cpp
src/Statistics.cpp
src/Statistics.h

+ Mark DEPRECATED and REMOVED APIs
+ Sync with CUDA 11.0 Update 1
+ Fix typos
+ Add `interactions` conversion type

[HIPIFY] CUDA Runtime API: add Versions: A|D|R

---

src/CUDA2HIP_Doc.cpp

Fix the error:
```c++
no matching conversion for functional-style cast from 'SmallString<128>' to 'std::__cxx11::string' (aka 'basic_string<char>')
```

[HIPIFY] Fix Linux build

---

README.md

+ Mention clang's bug [#47332](https://bugs.llvm.org/show_bug.cgi?id=47332) in README.md
+ CUDA 11.0 (before Update 1) is the latest stable CUDA release due to the clang's bug 47332
+ Update Dependencies, Building and Testing sections of README.md

[HIPIFY][doc] LLVM 11.0.0 is the latest stable release

---

src/CUDA2HIP_Perl.cpp

previously only files immediately in an excluded directory would be excluded
i.e. for excluded directory /foo/bar the file /foo/bar/fred would be excluded
but /foo/bar/fred/george would not since /foo/bar/fred was not in the exlcude
hashmap.
The fix now will keep finding parent direectories of the file until the current
directory is either "." or "/" or the direcory is found in the exclude map
/foo/bar/fred/george will look in the map for /foo/bar/fred (not find)
then  /foo/bar (find and exit)

[HIPIFY] Fixed Subdirectory Exclusion

---

bin/hipify-perl
src/CUDA2HIP_Driver_API_functions.cpp
src/CUDA2HIP_Driver_API_types.cpp
src/CUDA2HIP_Runtime_API_functions.cpp
src/CUDA2HIP_Runtime_API_types.cpp

+ Add missing functions and data types
+ Rename some HIP functions, for instance: `hipDrv...` -> `hipModule...`
+ Mark all lately supported functions and data types

[HIPIFY][HIP] Sync with the latest ROCclr 3.9.0

---

src/CUDA2HIP_Doc.cpp

[Reason] To not duplicate common HIP APIs for HIP versioning in DRIVER and RUNTIME sections of code

[HIPIFY][#234] Make hipVersionMap common for DRIVER and RUNTIME APIs

---

bin/hipify-perl
src/CUDA2HIP_Driver_API_types.cpp
src/CUDA2HIP_Runtime_API_types.cpp

+ Add missing data types
+ Rename Driver API analogues
+ Fix typos
TODO [HIP]:
+ HIPresourcetype_enum and all its values should be hipResourceType as long as they are equal
+ HIPaddress_mode_enum and all its values should be hipTextureAddressMode as long as they are equal
+ Add to hcc_detail\hip_runtime_api.h hipJitOption enum the following values:
hipJitGlobalSymbolNames
hipJitGlobalSymbolAddresses
hipJitGlobalSymbolCount

[HIPIFY][#234] Add versions for HIP Driver and Runtime APIs data types (Part 1)

---

src/ArgParse.cpp
src/ArgParse.h
src/CUDA2HIP_Doc.cpp
src/main.cpp

+ Add option --doc-format={full | strict}, which might be used only with --md or --csv options;
+ Default doc format is 'full'
+ Strict format differences:
Do not generate rows with unsupported API,
Do not generate 'A' and 'R' columns,
Set '+' instead of version in 'D' column

[HIPIFY] Support of CUDA2HIP docs generation in 'strict' format

---

README.md

+ CUDA 11.2.1 is supported
+ CuDNN 8.1.0 is supported
+ Update software versions
+ Tested on Windows and Ubuntu

[HIPIFY][doc] Update README.md

---

bin/hipify-perl
src/CUDA2HIP_Perl.cpp
tests/unit_tests/kernel_launch/kernel_launch_syntax.cu

+ Add support of function calls and typecasting as the CUDA launch parameters
+ Get rid of dim3() typecasting of CUDA launch Dg and Db arguments
+ Update kernel_launch_syntax.cu test with the supported cases
+ Update hipify-perl script accordingly
ToDo:
+ Implement transformations with nested function calls and typecasting as the CUDA launch parameters

[HIPIFY][perl][#294] Fix incorrect transformation of function call as the CUDA launch parameter

---

bin/hipify-perl
src/CUDA2HIP_Perl.cpp

+ Being used along with `>>` `-o` has a priority, so STDOUT will be empty

[HIPIFY][perl][#268] Add option `-o=filename`

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_functions.cpp
src/CUDA2HIP_Driver_API_types.cpp
src/HipifyAction.cpp
src/Statistics.cpp
src/Statistics.h
tests/unit_tests/casts/reinterpret_cast.cu

+ Add typecasting to the third functions' arg
+ Rewrite casting procedure in `HipifyActions`
+ Update the `reinterpret_cast.cu` test
+ Update `hipify-perl` and `CUDA_Driver_API_functions_supported_by_HIP.md` accordingly
+ Bump internal HIP version to 4.2.0

[HIPIFY][#304] Support of Stream Memory Operations (ROCm 4.2)

---

bin/hipify-perl
src/CUDA2HIP_Perl.cpp
src/CUDA2HIP_Scripting.h
src/HipifyAction.cpp

[Reason] Possible data loss after type-casting of the 3rd argument of the above functions, where CUDA's unsigned int value is explicitly type-casted to signed int
[ToDo] Add the corresponding warning in the documentation on the above functions

[HIPIFY][#304] Add warning for StreamWaitValue32(64) and StreamWriteValue32(64) functions

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_types.cpp
src/Statistics.cpp
src/Statistics.h

+ Add CUDA 11.3 to enums
+ Update CUDA_Driver_API_functions_supported_by_HIP.md accordingly

[HIPIFY] Support CUDA 11.3 Driver API types

---

src/Statistics.h

For instance, compiling hipify-clang by Visual Studio 2015 leads to the following error:
`error C2440: 'initializing': cannot convert from 'initializer list' to 'std::map<llvm::StringRef,cudaAPIversions,std::less<_Kty>,std::allocator<std::pair<const _Kty,_Ty>>>'`

[HIPIFY][fix] Fix building by old C++ compilers

---

bin/hipify-perl
doc/markdown/CUSPARSE_API_supported_by_HIP.md
src/CUDA2HIP_SPARSE_API_functions.cpp
src/CUDA2HIP_SPARSE_API_types.cpp

+ Add missing cuSPARSE functions
+ Add missing hipSPARSE data types
+ Update CUSPARSE_API_supported_by_HIP.md accordingly

[HIPIFY][SPARSE] Sync with hipSPARSE 4.2.0 (functions)

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_functions.cpp
src/CUDA2HIP_Runtime_API_types.cpp

+ Mark a few data types and functions as supported
+ Update CUDA_Runtime_API_functions_supported_by_HIP.md and CUDA_Driver_API_functions_supported_by_HIP.md accordingly

[HIPIFY] Sync with HIP-rocm-4.2.0

---

CMakeLists.txt
README.md
src/main.cpp

+ Only `-std=c++14` is set in all cases
+ MS VC starting 2015 is ok with `c++14`, previous versions are not supported
+ Minimum GNU C/C++ version now is 6.1 (was 5.4): README.md is updated accordingly
+ hipify-clang itself now works with `-std=c++14` by default as well
+ [Misc] `CMakeLists.txt` formatting

[HIPIFY] Get rid of building configs with -std=c++11

---

tests/run_test.bat

Workaround for the new error appeared with VS 16.10 release:
`..\VC\Tools\MSVC\14.29.30037\include\yvals_core.h(531,2): error GFDCF76F8: STL1002: Unexpected compiler version, expected CUDA 10.1 Update 2 or newer.`
ToDo: It might be better to do it in hipify-clang itself for Windows target only.

[HIPIFY][tests][win] Workaround for VS 16.10

---

README.md

+ All new APIs have been taken into account

[HIPIFY][doc] CUDA 11.3.1 is the latest supported release

---

src/Statistics.cpp

Fix the following compilation error that appeared with the latest LLVM trunk:
error: no member named 'lround' in namespace 'std'

[HIPIFY][fix][Linux] Add explicit include to <cmath>

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_types.cpp
tests/unit_tests/samples/2_Cookbook/11_texture_driver/texture2dDrv.cpp
tests/unit_tests/synthetic/driver_structs.cu

+ Revise and fix CUDA2HIP mapping for CUDA Driver API structs
+ Add first synthetic test driver_structs.cu for CUDA Driver API structs only
+ Update other tests, docs, and hipify-perl accordingly

[HIPIFY][tests][fix] Synthetic tests for CUDA Driver API structs

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_types.cpp
src/CUDA2HIP_Runtime_API_types.cpp
tests/unit_tests/synthetic/driver_structs.cu
tests/unit_tests/synthetic/runtime_structs.cu

+ Revise and fix CUDA2HIP mapping for CUDA Runtime and Driver API structs
+ Add synthetic test runtime_structs.cu for CUDA Runtime API structs only
+ Update other tests, docs, and hipify-perl accordingly

[HIPIFY][tests][fix] Synthetic tests for CUDA Runtime API structs

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_types.cpp

[Reason]
CUDA_VERSION has no 1 to 1 mapping to HIP_VERSION.
Some HIP APIs from the same HIP_VERSION may map to a particular CUDA_VERSION; some may not; thus, there is no actually mapping between CUDA_VERSION and HIP_VERSION.

[HIPIFY][fix][#372] Mark CUDA_VERSION as unsupported

---

bin/hipify-perl
doc/markdown/CUSPARSE_API_supported_by_HIP.md
src/CUDA2HIP_SPARSE_API_functions.cpp
src/CUDA2HIP_SPARSE_API_types.cpp

+ Add missing cuSPARSE types and functions
+ Update hipify-perl and cuSPARSE documentation
+ ToDo: Revise and add the rest of the missing cuSPARSE APIs since CUDA 11.2

[HIPIFY][SPARSE] Sync with hipSPARSE 4.3

---

bin/hipify-perl
doc/markdown/CUSPARSE_API_supported_by_HIP.md
src/CUDA2HIP_SPARSE_API_types.cpp

+ Update hipify-perl and SPARSE documentation accordingly

[HIPIFY][SPARSE][fix] Add missing APis appeared with CUDA 11.3.x

---

doc/markdown/CUDA_Device_API_supported_by_HIP.md
src/CUDA2HIP_Device_functions.cpp

+ Update `CUDA_Device_API_supported_by_HIP.md` accordingly

[HIPIFY][fix] Change `__funnelshift` functions HIP `added` version from 4.3 to 4.4

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_types.cpp
tests/unit_tests/samples/2_Cookbook/11_texture_driver/texture2dDrv.cpp
tests/unit_tests/synthetic/driver_functions.cu
tests/unit_tests/synthetic/driver_structs.cu

+ Start to map `CUarray` to `hipArray_t` instead of `hipArray*` (equivalent transformations)
+ Update other tests, docs, and hipify-perl

[HIPIFY][tests] Synthetic test for CUDA Driver API functions - Part 3

---

packaging/hipify-clang.txt

The intention is to make all the rocm packages depend on rocm-core to
enable eveerything to be removed cleanly by just removing the
rocm-core package.
Signed-off-by: Icarus Sparry <icarus.sparry@amd.com>

[HIPIFY] Add dependency on rocm-core

---

CMakeLists.txt

Requesting this change based on internal tickets SWDEV-287841 and SWDEV-287817. These aim to alleviate the issues resulting in assuming the default ROCm path.

Remove direct dependency on "/opt/rocm" path

---

src/ArgParse.cpp
src/CUDA2HIP_Doc.cpp
src/main.cpp

+ Additionally, apply sequential numbering for docs' sections (compact format only)
+ [fix] Add `-doc-format`option to hipifyOptions vector

[HIPIFY][#405] Implement `compact` doc-format

---

tests/unit_tests/synthetic/driver_enums.cu
tests/unit_tests/synthetic/runtime_enums.cu

+ Add '--skip-excluded-preprocessor-conditional-blocks' option to the tests which have the following conditional includes:
```c++
#if defined(_WIN32)
#include "windows.h"
#endif
```

[HIPIFY][tests][fix] Switch preprocessor's mode to regular for some OS-specific tests

---

tests/unit_tests/libraries/CUB/cub_01.cu
tests/unit_tests/libraries/CUB/cub_02.cu
tests/unit_tests/libraries/CUB/cub_03.cu

+ An issue observed on CUB starting 1.12:
`/root/cub/cub/device/dispatch/../../agent/agent_merge_sort.cuh:80:32: error: use of undeclared identifier 'THRUST_NS_QUALIFIER'`

[HIPIFY][tests][fix] Fix CUB tests failed on THRUST_NS_QUALIFIER

---

src/CUDA2HIP_Doc.cpp
src/Statistics.cpp
src/Statistics.h

+ Add `hipVersions experimental = HIP_0` to the `struct hipAPIversions`
+ Add `HIP_LATEST = HIP_4050` to `enum hipVersions`
+ Add "Experimental" (E) column for HIP API only in the generated CUDA2HIP documents' tables

[HIPIFY][#430] Introducing HIP_EXPERIMENTAL attribute

---

src/ArgParse.cpp
src/ArgParse.h
src/HipifyAction.cpp
src/main.cpp
tests/unit_tests/graph/simple_mechs.cu
tests/unit_tests/synthetic/driver_enums.cu
tests/unit_tests/synthetic/driver_structs.cu
tests/unit_tests/synthetic/runtime_enums.cu
tests/unit_tests/synthetic/runtime_structs.cu

+ Populate some tests with the `--experimental` option
[BEHAVIOR]
+ If not set (by default) API marked as `HIP_EXPERIMENTAL` are not hipified, a warning `CUDA identifier is experimental in HIP. To hipify it, use the '--experimental' option.` is reported.
+ If set silent hipification of all APIs marked as `HIP_EXPERIMENTAL` takes place.

[HIPIFY][#434] Introduce '--experimental' option

---

src/HipifyAction.cpp
tests/unit_tests/casts/reinterpret_cast.cu
tests/unit_tests/synthetic/driver_functions.cu

Affected functions: hipStreamWaitValue32, hipStreamWaitValue64, hipStreamWriteValue32, hipStreamWriteValue64.
Their 3rd args was `int` become `uint` as in CUDA analogues; thus remove casting to `int` while hipifying.
+ Update affected tests

[HIPIFY][fix] Undo args typecasting for 4 Driver API functions

---

bin/hipify-perl
src/CUDA2HIP_Perl.cpp

Affected functions: `hipStreamWaitValue32`, `hipStreamWaitValue64`, `hipStreamWriteValue32`, `hipStreamWriteValue64`.
Their 3rd args was `int` become `uint` as in CUDA analogues; thus remove casting to `int` while hipifying.
+ Update hipify-perl generation and the generated hipify-perl script

[HIPIFY][fix][perl] Undo args typecasting for 4 Driver API functions - Part 2

---

doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
src/CUDA2HIP_Doc.cpp

It happens with HIP API common for CUDA RT API and Device API when for one CUDA API (for instance, RT) HIP API is supported and for another is not (due to differences in function signatures, for example). As long as the HIP API name is the same, HIP versions for the unsupported CUDA API shouldn't be printed.
+ Update the affected doc CUDA_Driver_API_functions_supported_by_HIP.md

[HIPIFY][#460][fix] Stop printing HIP API versions if CUDA API is unsupported

---

README.md

+ Exclude obsolete `LLVM_SOURCE_DIR` and unneeded `LLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN=ON` from LLVM cmake command lines
+ Add `cd` and `mkdir` commands for building HIPIFY and LLVM
+ Recommend using `build` and `dist` folders at the same level as `hipify` and `llvm`
+ Fix a few typos
P.S.
`LLVM_TARGETS_TO_BUILD` still needs `'X86'` (on Linux only) for LLVM build to build HIPIFY successfully

[HIPIFY][doc] Update building instructions

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_functions.cpp
src/CUDA2HIP_Runtime_API_functions.cpp
tests/unit_tests/synthetic/driver_functions.cu

+ Add new supported APIs, mark them as experimental
[NOTE] Some Graph functions in CUDA Driver API do not have analogues in CUDA Runtime API due to CUcontext as the last argument:
cuGraphAddMemcpyNode, cuGraphAddMemsetNode, cuGraphExecMemcpyNodeSetParams, cuGraphExecMemsetNodeSetParams

[HIPIFY] Sync with the upcoming HIP-rocm-5.0.0 - Part 4

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_types.cpp
src/CUDA2HIP_Scripting.h
src/HipifyAction.cpp
tests/unit_tests/synthetic/driver_functions.cu

For now, there was only typecasting of function arguments when hipifying CUDA function calls.
`cuOccupancyMaxPotentialBlockSize` is the first precedent when one of the arguments has to be removed from the function call.
Here is its implementation in HIP Runtime for the fallback NVIDIA path:
```c++
//TODO - Match CUoccupancyB2DSize
inline static hipError_t hipModuleOccupancyMaxPotentialBlockSize(int* gridSize, int* blockSize,
hipFunction_t f, size_t dynSharedMemPerBlk,
int blockSizeLimit){
return hipCUResultTohipError(cuOccupancyMaxPotentialBlockSize(gridSize, blockSize, f, NULL,
dynSharedMemPerBlk, blockSizeLimit));
}
```
`CUoccupancyB2DSize` data type is not implemented currently in HIP RT. Nonetheless, to perform hipification from `cuOccupancyMaxPotentialBlockSize` to …

[HIPIFY] Implement arg removal from a function call

---

tests/unit_tests/synthetic/driver_functions.cu

[Failure][Linux]
```shell
/tmp/driver_functions.cu-50e2d3.hip:984:12: error: no matching function for call to 'cuStreamGetCaptureInfo'
result = cuStreamGetCaptureInfo(stream, &streamCaptureStatus, &ull);
^~~~~~~~~~~~~~~~~~~~~~
/usr/local/cuda/include/cuda.h:11677:18: note: candidate function not viable: no known conversion from 'unsigned long long *' to 'cuuint64_t *' (aka 'unsigned long *') for 3rd argument
CUresult CUDAAPI cuStreamGetCaptureInfo(CUstream hStream, CUstreamCaptureStatus *captureStatus_out, cuuint64_t *id_out);
^
/tmp/driver_functions.cu-50e2d3.hip:1055:12: error: no matching function for call to 'cuStreamGetCaptureInfo_v2'
result = cuStreamGetCaptureInfo_v2(stream, &streamCaptureStatus, &ull, &graph, &pGraphNode, &bytes);
^~~~~~~~~~~~~~~~~~~~~~~~~ …
```

[HIPIFY][tests][fix][Linux] Fix failure in driver_functions.cu due to CUDA's `cuuint64_t`

---

CMakeLists.txt
packaging/hipify-clang.postinst
packaging/hipify-clang.prerm
packaging/hipify-clang.rpm_post
packaging/hipify-clang.rpm_postun

Make use of the CPACK_PACKAGING_INSTALL_PREFIX instead of the absolute paths introduced by the post  install scripts in -
https://github.com/ROCm-Developer-Tools/HIPIFY/commit/cf84714be4f4c6eef0c1bc6c7939630917d52084

[HIPIFY][fix] Remove the absolute paths in post install scripts

---

README.md

+ Tested on Windows 10 and Ubuntu 21.10

[HIPIFY][doc] LLVM 13.0.1 is the latest supported LLVM release

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_functions.cpp
tests/unit_tests/synthetic/driver_functions.cu

+ `hipHostAlloc` to which `cuMemAllocHost` was erroneously mapped before has even different signature
+ Perform the mapping change although `hipMemAllocHost` has been deprecated since its first appearance in ROCm HIP 3.0.0
+ Update tests, docs, and hipify-perl accordingly

[HIPIFY][#502][fix] Change `cuMemAllocHost` mapping to `hipMemAllocHost`

---

bin/hipify-perl
doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
src/CUDA2HIP_Runtime_API_functions.cpp
tests/unit_tests/device/device_symbols.cu

+ `hipMallocHost` to which `cudaMallocHost` was erroneously mapped before has even different signature
+ Update tests, docs, and hipify-perl accordingly

[HIPIFY][#499][fix] Change `cudaMallocHost` mapping to `hipHostMalloc`

---

CMakeLists.txt

[Reason]
MSVC and Windows related driver stuff was moved from `clangDriver` lib to `LLVMWindowsDriver` lib.
The change affects both `Linux` and `Windows` builds as clang Driver encapsulates all `ToolChains` including `MSVC`.

[HIPIFY][#507][fix] Introduce `LLVMWindowsDriver` lib for linking

---

CMakeLists.txt

[The affecting LLVM change]
____
SHA-1: c5fb05f663f2ac0cbedb318d03b91d44900ab9de
* Reland: Make lld-link work in a non-MSVC shell, add /winsysroot:
This relands 73e585e44d (and 0574b5fc657451), with a fix for
the failing test (by using Optional<StringRef>s instead of
making StringRef::empty() mean absence of value).
Differential Revision: https://reviews.llvm.org/D118070
____
+ This change shouldn't be presented in 14.x.x LLVM releases
+ To link hipify-clang correctly with LLVM >= 15 pull the latest LLVM sources

[HIPIFY][#507][fix] Link with `LLVMWindowsDriver` lib if LLVM version >= 15.0.0

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_functions.cpp
src/CUDA2HIP_Driver_API_types.cpp
src/CUDA2HIP_Runtime_API_functions.cpp
src/CUDA2HIP_Runtime_API_types.cpp
src/Statistics.cpp
src/Statistics.h
tests/unit_tests/synthetic/driver_enums.cu
tests/unit_tests/synthetic/driver_functions.cu

+ Remove mark `HIP_EXPERIMENTAL` from all HIP-rocm-5.0.0 APIs
+ Add newly supported APIs, mark them as `HIP_EXPERIMENTAL`

[HIPIFY] Sync with the upcoming HIP-rocm-5.1.0

---

tests/lit.cfg

[Reason] Starting with CUDA SDK Toolkit 11.6 Samples are released separately from SDK on GitHub: https://github.com/nvidia/cuda-samples
To test hipify-clang against CUDA 11.6 and newer, CUDA SDK samples of the corresponding version should be downloaded from https://github.com/NVIDIA/cuda-samples/releases, and the contains of the root folder in the archive should be extracted to the CUDA_TOOLKIT_ROOT_DIR corresponding to CUDA_SDK_ROOT_DIR (or equal to it in case of Linux)
P.S.
Actually, only `GL` subfolder is needed in CUDA SDK samples for synthetic tests dealing with GL interop (`#include <GL/glew.h>`)

[HIPIFY][tests] Add CUDA 11.6 samples support to lit.cfg

---

README.md

+ Update 3rd parties tools versions
+ Tested on Windows 10 and Ubuntu 21.10

[HIPIFY][doc] CUDA 11.6.1 is the latest supported release

---

CMakeLists.txt
hipify-backward-compat.cmake
packaging/hipify-clang.txt

With file reorganization feature, hipify package installed in /opt/rocm-ver instead of /opt/rocm-ver /hip
To maintain backward compatibility, the previous location /opt/rocm-ver/hip will have soft link for binaries and wrapper files for header files

[HIPIFY][build] File Reorganization with backward compatibility

---

bin/hipify-perl
src/CUDA2HIP_Perl.cpp

+ Updated regenerated hipify-perl accordingly
[ToDo] Populate with header file names, APIs without prefixes, etc.

[HIPIFY][#525][perl] Populate `convertedTags` pattern with libraries' prefixes

---

src/main.cpp

Clang's system header files shipped with hipify-clang packages are moved:
`<hipify-clang_dir>/bin/include` -> `<hipify-clang_dir>/../include/hipify`
Previous path `<hipify-clang_dir>/bin/include` is not excluded from searching by `hipify-clang` for backward compatibility.
[Reason]
[SWDEV-291455] File reorganization for all ROCm HIP packages, where `../include` is the `include` subfolder for all ROCm HIP packages, including `hipify` package.
This change unblocks #528 for merging.

[HIPIFY][SWDEV-291455][#528] File reorganization

---

src/HipifyAction.cpp

+ To build hipify-clang correctly with LLVM >= 15git pull the latest LLVM sources
+ Tested on Windows 10 and Ubuntu 21

[HIPIFY][compatibility][fix] LLVM 15.0.0git compatibility support

---

CMakeLists.txt
src/HipifyAction.cpp

+ To build hipify-clang against `trunk LLVM (15.0.0git)` nothing to do else
+ To build hipify-clang against `trunk LLVM (15.0.0git)` older than `d79ad2f1dbc2db63121620f55d6cfa915f2733ac` (2022.04.11, DR: https://reviews.llvm.org/D123574) `-DSWDEV_331863=ON` should be added to hipify-clang's cmake command line
[ToDo] Remove `SWDEV_331863` related guards from `CMakeLists.txt` and `HipifyAction.cpp` when the blocker `SWDEV_331863` is overcome

[HIPIFY][#531][SWDEV_331863][temporary][workaround] Add a workaround for the `SWDEV_331863` blocker

---

README.md

+ `LLVM 3.x` is not supported anymore, the oldest supported release is `LLVM 4.0.0`
+ `CUDA 7.0` is still supported, but the oldest recommended release is `CUDA 8.0`
+ Versions of the used tools are also updated
+ Extended testing on `Windows 10`/`VS 2019, 2022` and `Ubuntu 21.10`/`GCC 11.2.0`

[HIPIFY] README.md update: `LLVM 14.0.3` and `CUDA 11.6.2` are the latest supported releases

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_functions.cpp
src/CUDA2HIP_Driver_API_types.cpp
src/CUDA2HIP_Runtime_API_functions.cpp
src/CUDA2HIP_Runtime_API_types.cpp
src/Statistics.cpp
src/Statistics.h
tests/unit_tests/synthetic/driver_enums.cu
tests/unit_tests/synthetic/driver_structs.cu
tests/unit_tests/synthetic/driver_typedefs.cu
tests/unit_tests/synthetic/runtime_enums.cu
tests/unit_tests/synthetic/runtime_structs.cu
tests/unit_tests/synthetic/runtime_typedefs.cu

+ Add new HIP versions 5.1.1 (no changes in APIs) and 5.2.0 (API changes in progress)
+ Unmark experimental APIs
+ Fix APIs with missing HIP versions

[HIPIFY] Sync with the upcoming HIP-rocm-5.2.0 - Part 1 - Types

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_types.cpp
tests/unit_tests/synthetic/driver_enums.cu
tests/unit_tests/synthetic/driver_structs.cu
tests/unit_tests/synthetic/driver_typedefs.cu

[HIPIFY] Sync with the upcoming HIP-rocm-5.2.0 - Part 6 (final) - Types

---

tests/unit_tests/synthetic/driver_functions.cu

+ Use `unsigned long long` type in CUDA functions, where it is used as `unsigned long long`
+ Situations where `cuuint64_t` are used left unchanged in tests:
```cpp
#ifdef _MSC_VER
typedef unsigned __int32 cuuint32_t;
typedef unsigned __int64 cuuint64_t;
#else
#include <stdint.h>
typedef uint32_t cuuint32_t;
typedef uint64_t cuuint64_t;
#endif
```
So, for 64bit compilation `unsigned __int64` for `cuuint64_t` on Windows is always defined as `unsigned long long`; `uint64_t` for `cuuint64_t` on Linux is defined as `unsigned long`

[HIPIFY][#551][fix] Fix the failed synthetic test `driver_functions.cu`

---

README.md

+ Update 3rd parties tools versions
+ Tested on Windows 10 and Ubuntu 21.10

[HIPIFY][doc] CUDA 11.7 is the latest supported release
