bin/hipify-perl
src/CUDA2HIP_BLAS_API_functions.cpp

+ Based on: https://github.com/ROCmSoftwarePlatform/hipBLAS/pull/146

[HIPIFY][BLAS] sync with hipBLAS's #146 "Matching rocBLAS 3.0 Functionality" (#99)

---

bin/hipify-perl
src/CUDA2HIP_BLAS_API_functions.cpp

+ https://github.com/ROCmSoftwarePlatform/hipBLAS/pull/175
+ Batched: getrf, getrs, and geqrf

[HIPIFY][BLAS] Sync with hipBLAS's #175 "rocSOLVER support" (#104)

---

bin/hipify-perl
src/CUDA2HIP_BLAS_API_functions.cpp

Update hipify-perl accordingly

[HIPIFY][BLAS] Add syr2_v2 functions support

---

README.md

+ Tested with the latest LLVM 11.0.0git, cmake and python

[HIPIFY][doc] Update README.md

---

src/CUDA2HIP_Driver_API_functions.cpp
src/CUDA2HIP_Driver_API_types.cpp
src/HipifyAction.cpp
src/Statistics.cpp
src/Statistics.h

+ Mark all CUDA Driver API deprecated identifiers
[ToDo] Mark all CUDA Runtime API deprecated identifiers

[HIPIFY][#111] Teach HIPIFY to warn about deprecated CUDA APIs

---

src/CUDA2HIP_Runtime_API_functions.cpp
src/CUDA2HIP_Runtime_API_types.cpp

[ToDo] Teach hipify-perl to warn about deprecated CUDA APIs as well

[HIPIFY][#111] Mark all CUDA Runtime API deprecated identifiers

---

src/CUDA2HIP_Perl.cpp

[ToDo] Update hipify-perl in HIP repo as well

[HIPIFY][#118] Teach hipify-perl to warn about unsupported CUDA APIs

---

bin/hipify-perl
src/CUDA2HIP_BLAS_API_functions.cpp

Sync with https://github.com/ROCmSoftwarePlatform/hipBLAS/pull/234
update hipify-perl accordingly

[HIPIFY][BLAS] Add a support for vector and matrix async functions

---

bin/hipify-perl
src/CUDA2HIP_BLAS_API_functions.cpp

Sync with https://github.com/ROCmSoftwarePlatform/hipBLAS/pull/227
Update hipify-perl accordingly

[HIPIFY][BLAS] Adding gemm_ex batched functions

---

bin/hipify-perl
src/CUDA2HIP_BLAS_API_functions.cpp

Update hipify-perl accordingly
[ToDo] Update CUBLAS_API_supported_by_HIP.md accordingly

[HIPIFY][BLAS] Sync with state-of-the-art rocBLAS and hipBLAS libraries

---

README.md

Tested with CUDA 11.0 Release, LLVM 10.0.1-rc4, LLVM 12.0.0git, cmake 3.18.0, and python 3.8.4

[HIPIFY][doc] Update Readme.md (versioning)

---

bin/hipify-perl
src/CUDA2HIP_FFT_API_functions.cpp

[ToDo][HIP] Update HIP's CUFFT_API_supported_by_HIP.md accordingly

[HIPIFY] Sync cuFFT with hipFFT

---

bin/hipify-perl

Update auto-generated hipify-perl based on #181 "[HIPIFY] Added directory and file exclusion, updated whitelist".

[HIPIFY] Sync with #181

---

src/ArgParse.cpp
src/ArgParse.h
src/CUDA2HIP.h
src/CUDA2HIP_Doc.cpp
src/CUDA2HIP_SPARSE_API_functions.cpp
src/CUDA2HIP_Scripting.h
src/main.cpp

+ Under the options --md and --csv (in progress)
+ Add OO infrastructure for auto-generation
+ Generate section headers for all markdown docs
+ Fix typos, add needed exports

[HIPIFY][#172] Initial documentation auto-generation

---

src/CUDA2HIP.cpp
src/CUDA2HIP.h
src/CUDA2HIP_Doc.cpp
src/Statistics.cpp

ToDo:
+ csv docs generation
+ Add versions for the rest of APIs: Driver, Runtime Types, Complex, BLAS, FFT, DNN, RAND

[HIPIFY][#172] Markdown docs generation is implemented

---

bin/hipify-perl
src/CUDA2HIP_BLAS_API_functions.cpp

+ Add CUDA versioning for cuBLAS API
+ Affects auto-generated CUBLAS_API_supported_by_HIP.md
+ Remove non-CUDA functions
+ Update hipify-perl

[HIPIFY][#172][BLAS] cuBLAS API functions versioning

---

src/CUDA2HIP_RAND_API_functions.cpp

+ Add CUDA versioning for cuRAND API
+ Affects auto-generated CURAND_API_supported_by_HIP.md

[HIPIFY][#172][RAND] cuRAND API versioning

---

src/CUDA2HIP_FFT_API_functions.cpp

+ Add CUDA versioning for cuFFT API functions
+ Affects auto-generated CUFFT_API_supported_by_HIP.md

[HIPIFY][#172][FFT] cuFFT API functions versioning

---

src/CUDA2HIP_RAND_API_types.cpp

+ Add CUDA versioning for cuRAND API Data Types
+ Affects auto-generated CURAND_API_supported_by_HIP.md

[HIPIFY][#172][RAND] cuRAND API Data Types versioning

---

README.md

+ Add a link to LLVM's requirements for the building software
+ Fix typos

[HIPIFY][doc] README.md update

---

src/CUDA2HIP_Perl.cpp
src/Statistics.cpp
src/Statistics.h

+ Modify hipify-perl script generation

[HIPIFY][perl] Add warnings on the removed CUDA entities

---

bin/hipify-perl
src/CUDA2HIP_Driver_API_functions.cpp
src/Statistics.cpp
src/Statistics.h

+ Add new module: CONV_STREAM_ORDERED_MEMORY

[HIPIFY] CUDA 11.2 Driver API functions support

---

src/ArgParse.cpp
src/CUDA2HIP_Doc.cpp

Options:
--csv - Generate documentation in csv format
--md - Generate documentation in Markdown format
--csv --md - Generate documentation in both supported formats

[HIPIFY][#172] Automated documentation generation in csv file format

---

src/CUDA2HIP_Doc.cpp

In case of the unsupported whole API section

[HIPIFY][fix] Print "Unsupported" instead of single table header

---

bin/hipify-perl
src/CUDA2HIP_Perl.cpp
tests/unit_tests/kernel_launch/kernel_launch_syntax.cu

+ Fix generateKernelLaunch() for hipify-perl
+ Add synthetic test kernel_launch_syntax.cu for both hipify-clang and hipify-perl

[HIPIFY][#246] Fix kernel launching transformation in hipify-perl

---

bin/hipify-perl
src/CUDA2HIP_Perl.cpp

[HIPIFY][perl][#275] Distinguish CUDA and cuDNN in warnings

---

bin/hipify-perl
doc/markdown/CUBLAS_API_supported_by_HIP.md
src/CUDA2HIP_BLAS_API_functions.cpp

+ Update CUBLAS_API_supported_by_HIP.md accordingly

[HIPIFY][SPARSE] Sync with hipBLAS 4.1.0

---

bin/hipify-perl
src/CUDA2HIP_Perl.cpp
src/CUDA2HIP_Scripting.h
src/HipifyAction.cpp

+ Add support of SMO to hipify-perl as well
+ Refactor related code a bit

[HIPIFY][perl][#304] Support of Stream Memory Operations

---

bin/hipify-perl
src/CUDA2HIP_Perl.cpp

+ Bump hipify-perl version to 4.2.0

[HIPIFY][perl] Minor enhancements

---

README.md

[HIPIFY][doc] LLVM 12.0.0 is the latest supported release

---

README.md

[HIPIFY][doc] CUDA 11.3 is the latest supported release

---

bin/hipify-perl
doc/markdown/CUDNN_API_supported_by_HIP.md
src/CUDA2HIP_DNN_API_types.cpp
src/Statistics.cpp
src/Statistics.h

+ Update CUDNN_API_supported_by_HIP.md accordingly

[HIPIFY][DNN] cuDNN 8.2.0 API data types support

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_types.cpp
src/CUDA2HIP_Runtime_API_types.cpp

+ Update MD documentation and hipify-perl accordingly

[HIPIFY] Sync with HIP 4.3.0 (data types only)

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_types.cpp
src/CUDA2HIP_Runtime_API_types.cpp

+ Update md documentation and hipify-perl accordingly

[HIPIFY] Sync with HIP 4.3.0 (data types only) - continuation

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_functions.cpp
src/CUDA2HIP_Runtime_API_functions.cpp

+ Update md documentation and hipify-perl accordingly

[HIPIFY] Sync with HIP 4.3.0 (functions only)

---

README.md

[HIPIFY] The latest supported version of cuDNN is 8.2.1

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_functions.cpp
src/Statistics.cpp
src/Statistics.h

+ Add CUDA 11.4 to enums
+ Update CUDA_Driver_API_functions_supported_by_HIP.md accordingly

[HIPIFY] Add support for CUDA 11.4 Driver API functions only

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_functions.cpp
src/CUDA2HIP_Runtime_API_functions.cpp
tests/unit_tests/device/device_symbols.cu

+ Update tests, docs, and hipify-perl accordingly

[HIPIFY][#349] Fix incorrect mapped cudaHostAlloc and cudaMallocHost

---

README.md

[HIPIFY][doc] LLVM 12.0.1 is the latest supported release

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_types.cpp
src/CUDA2HIP_Runtime_API_types.cpp
tests/unit_tests/synthetic/driver_structs.cu

+ Update tests, docs, and hipify-perl accordingly

[HIPIFY][fix] Add missing Graph types for HIP 4.3 release

---

bin/hipify-perl
doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_types.cpp
src/CUDA2HIP_Runtime_API_types.cpp

+ Update CUDA_Runtime_API_functions_supported_by_HIP.md accordingly

[HIPIFY] Add support for CUDA 11.4 Runtime API data types only

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_types.cpp
tests/unit_tests/synthetic/driver_typedefs.cu

+ Revise and fix CUDA2HIP mapping for CUDA Driver typedefs
+ Add synthetic test driver_typedefs.cu for CUDA Driver API typedefs only
+ Update docs and hipify-perl accordingly

[HIPIFY][tests][fix] Synthetic tests for CUDA Driver API typedefs

---

README.md

+ All new APIs have been taken into account

[HIPIFY][doc] CUDA 11.4 is the latest supported release

---

tests/unit_tests/graph/simple_mechs.cu

ToDo: Update cudaGraphAddDependencies call when its support appears

[HIPIFY][tests] Add first graph test simple_mechs.cu

---

bin/hipify-perl
doc/markdown/CUFFT_API_supported_by_HIP.md
src/CUDA2HIP.cpp
src/CUDA2HIP_FFT_API_types.cpp

+ Update hipify-perl and CUFFT_API_supported_by_HIP.md accordingly

[HIPIFY][FFT] Add cufftXt support (data types only)

---

src/CUDA2HIP_Driver_API_types.cpp
src/CUDA2HIP_Runtime_API_types.cpp

+ Annotating
+ No changes in scripts or docs because the changed APIs are yet unsupported

[HIPIFY][fix] Unify in HIP some new CUDA Driver and Runtime APIs

---

src/CUDA2HIP_Runtime_API_types.cpp
tests/unit_tests/synthetic/runtime_enums.cu

+ Finish with a synthetic test runtime_enums.cu for CUDA Runtime API enums only

[HIPIFY][tests] Synthetic tests for CUDA Runtime API enums - Part 4

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_functions.cpp
tests/unit_tests/synthetic/driver_functions.cu

+ Fix supported/unsupported APIs
+ Update docs and hipify-perl

[HIPIFY][tests] Synthetic test for CUDA Driver API functions - Part 1

---

bin/hipify-perl
doc/markdown/CUBLAS_API_supported_by_HIP.md
src/CUDA2HIP_BLAS_API_functions.cpp

+ Update docs and hipify-perl accordingly

[HIPIFY][BLAS] Sync with cuBLAS 11.4.2

---

README.md

[HIPIFY][doc] CUDA 11.4.2 is the latest supported release

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_functions.cpp
src/CUDA2HIP_Runtime_API_functions.cpp

+ Update docs and hipify-perl accordingly

[HIPIFY][HIP] Sync with HIP 4.5 - Part 2

---

tests/unit_tests/synthetic/driver_defines.cu
tests/unit_tests/synthetic/driver_enums.cu
tests/unit_tests/synthetic/driver_functions.cu
tests/unit_tests/synthetic/driver_structs.cu
tests/unit_tests/synthetic/driver_typedefs.cu
tests/unit_tests/synthetic/runtime_defines.cu
tests/unit_tests/synthetic/runtime_enums.cu
tests/unit_tests/synthetic/runtime_structs.cu
tests/unit_tests/synthetic/runtime_typedefs.cu

+ `stdio.h` was not found on some configs

[HIPIFY][tests][fix] Add missing include

---

tests/lit.cfg

The rule is as following:
{ == 0 | upper() == "OFF" | not set} = FALSE
{set AND != 0 AND upper() != "OFF" } = TRUE

[HIPIFY][#425][tests][fix] Fix conditions with "boolean" defines which came from cmake to lit.cfg

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_functions.cpp
tests/unit_tests/synthetic/driver_functions.cu

+ Fix supported/unsupported APIs
+ Update docs and hipify-perl

[HIPIFY][#407][tests] Synthetic test for CUDA Driver API functions - Part 6

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_functions.cpp
tests/unit_tests/synthetic/driver_functions.cu

+ Fix supported/unsupported APIs
+ Update docs and hipify-perl

[HIPIFY][tests][fix] Synthetic test for CUDA Driver API functions - Part 7

---

README.md

[HIPIFY][doc] Ubuntu 21 is supported

---

README.md

+ Update 3rd parties tools versions

[HIPIFY][doc] CUDA 11.5.1 is the latest supported release

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_functions.cpp
src/CUDA2HIP_Driver_API_types.cpp
src/CUDA2HIP_Runtime_API_functions.cpp
src/CUDA2HIP_Runtime_API_types.cpp
tests/unit_tests/synthetic/driver_enums.cu
tests/unit_tests/synthetic/driver_functions.cu
tests/unit_tests/synthetic/runtime_enums.cu

+ Add new supported APIs, mark them as experimental

[HIPIFY] Sync with the upcoming HIP-rocm-5.0.0 - Part 3

---

src/HipifyAction.cpp
tests/unit_tests/synthetic/driver_functions.cu

+ Add cuOccupancyMaxPotentialBlockSizeWithFlags to FuncArgCasts list
+ Add the corresponding test in driver_functions.cu

[HIPIFY] Add yet another function support with the argument removal

---

README.md

+ Tested on Windows 10 and Ubuntu 21.10

[HIPIFY][doc] LLVM 14.0.0 is the latest supported LLVM release

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_types.cpp
src/CUDA2HIP_Runtime_API_types.cpp
tests/unit_tests/synthetic/driver_enums.cu
tests/unit_tests/synthetic/runtime_enums.cu

[HIPIFY] Sync with the upcoming HIP-rocm-5.2.0 - Part 3 - Types

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_types.cpp
src/CUDA2HIP_Runtime_API_types.cpp
tests/unit_tests/synthetic/driver_enums.cu
tests/unit_tests/synthetic/driver_structs.cu
tests/unit_tests/synthetic/runtime_enums.cu
tests/unit_tests/synthetic/runtime_structs.cu

[HIPIFY] Sync with the upcoming HIP-rocm-5.2.0 - Part 4 - Types

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_types.cpp
src/CUDA2HIP_Runtime_API_types.cpp
tests/unit_tests/synthetic/driver_enums.cu
tests/unit_tests/synthetic/driver_structs.cu
tests/unit_tests/synthetic/runtime_enums.cu
tests/unit_tests/synthetic/runtime_structs.cu

[HIPIFY] Sync with the upcoming HIP-rocm-5.2.0 - Part 5 - Types

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_functions.cpp
src/CUDA2HIP_Runtime_API_functions.cpp
tests/unit_tests/synthetic/driver_functions.cu
tests/unit_tests/synthetic/runtime_functions.cu

+ Rename some HIP APIs
+ Add new synthetic test `runtime_functions.cu`

[HIPIFY] Sync with the upcoming HIP-rocm-5.2.0 - Part 1 - Functions

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_functions.cpp
src/CUDA2HIP_Runtime_API_functions.cpp
tests/unit_tests/synthetic/driver_functions.cu
tests/unit_tests/synthetic/runtime_functions.cu

[HIPIFY] Sync with the upcoming HIP-rocm-5.2.0 - Part 2 - Functions

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_functions.cpp
src/CUDA2HIP_Runtime_API_functions.cpp
tests/unit_tests/synthetic/driver_functions.cu
tests/unit_tests/synthetic/runtime_functions.cu

[HIPIFY] Sync with the upcoming HIP-rocm-5.2.0 - Part 3 - Functions

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_functions.cpp
src/CUDA2HIP_Driver_API_types.cpp
src/CUDA2HIP_Runtime_API_functions.cpp
tests/unit_tests/synthetic/driver_enums.cu
tests/unit_tests/synthetic/driver_functions.cu
tests/unit_tests/synthetic/driver_typedefs.cu
tests/unit_tests/synthetic/runtime_functions.cu

+ Rename and fix some HIP APIs

[HIPIFY] Sync with the upcoming HIP-rocm-5.2.0 - Part 4 (final) - Functions

---

bin/hipify-perl
src/CUDA2HIP.h
src/CUDA2HIP_Perl.cpp

+ Update regenerated `hipify-perl` script

[HIPIFY][perl][fix] `hipify-perl -version`: always print the latest supported HIP version

---

bin/hipify-perl
doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
src/CUDA2HIP_Driver_API_functions.cpp
tests/unit_tests/synthetic/driver_functions.cu

+ Update driver_functions.cu test
+ Update CUDA_Driver_API_functions_supported_by_HIP.md accordingly
+ Fix typo

[HIPIFY] Add support for CUDA 11.7 Driver API functions only
